# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # Increase boot timeout to 600s (default is 300s) to allow K8s heavy processes to start
  config.vm.boot_timeout = 1200

  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.

  config.vm.define "master" do |master|
    master.vm.box = "ubuntu/jammy64"
    master.vm.hostname = "master"
    master.vm.network "private_network", ip: "192.168.56.10"

    master.vm.provider "virtualbox" do |vb|
      vb.name = "master"
      vb.memory = "6144"
      vb.cpus = "4"
    end
    
    master.vm.provision "shell", path: "install_k8s.sh"
  end

  config.vm.define "worker" do |worker|
    worker.vm.box = "ubuntu/jammy64"
    worker.vm.hostname = "worker"
    worker.vm.network "private_network", ip: "192.168.56.11"

    worker.vm.provider "virtualbox" do |vb|
      vb.name = "worker"
      vb.memory = "6144"
      vb.cpus = "4"
    end

    worker.vm.provision "shell", path: "install_k8s.sh"
  end

  config.vm.define "haproxy" do |haproxy|
    haproxy.vm.box = "ubuntu/jammy64"
    haproxy.vm.hostname = "haproxy"
    haproxy.vm.network "private_network", ip: "192.168.56.12"

    haproxy.vm.provider "virtualbox" do |vb|
      vb.name = "haproxy"
      vb.memory = "2048"
      vb.cpus = "2"
    end
  end
end
