apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vdt-go-app.fullname" . }}
  labels:
    app: {{ include "vdt-go-app.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "vdt-go-app.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "vdt-go-app.fullname" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "vdt-go-app.fullname" . }}-config
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
